name: built_bloc
version: 0.3.5
author: Aloïs Deniel <alois.deniel@outlook.com>
description: Generates the BLoC boilerplate.
homepage: https://github.com/aloisdeniel/built_bloc

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  rxdart: ^0.22.0
  meta: ^1.1.6