name: built_bloc_generator
version: 0.4.1
author: Aloïs Deniel <alois.deniel@outlook.com>
description: Generates the BLoC boilerplate.
homepage: https://github.com/aloisdeniel/built_bloc
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.34.0 <0.39.0'
  build: ^1.0.0
  build_config: '>=0.3.1 <0.5.0'
  code_builder: ^3.1.3
  dart_style: ^1.2.2
  built_bloc: ^0.4.1
  path: ^1.3.2 
  source_gen: ^0.9.0
  meta: ^1.1.6 

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.3
  logging: ^0.11.3+1
  test: ^1.0.0
  yaml: ^2.1.13