name: built_bloc_generator
version: 0.4.2
description: Generates the BLoC boilerplate.
homepage: https://github.com/aloisdeniel/built_bloc
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.40.0
  build: ^1.0.0
  build_config: '>=0.3.1 <0.5.0'
  code_builder: ^3.5.0
  dart_style: ^1.2.2
  built_bloc: ^0.4.2
  path: ^1.7.0
  source_gen: ^0.9.7
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.3
  logging: ^0.11.3+1
  test: ^1.0.0
  yaml: ^2.1.13