name: built_bloc_generator
version: 0.2.7-dev
author: Aloïs Deniel <alois.deniel@outlook.com>
description: Generates the BLoC boilerplate.
homepage: https://github.com/aloisdeniel/built_bloc
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.32.2 <0.35.0'
  build: '>=0.12.6 <2.0.0'
  build_config: '>=0.2.6 <0.4.0'
  code_builder: ^3.1.3
  dart_style: ^1.2.2
  rxdart: ^0.20.0
  built_bloc: ^0.2.7-dev
  meta: ^1.1.6
  path: ^1.3.2 
  source_gen: ^0.9.0 

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.0
  build_verify: ^1.1.0
  build_web_compilers: ^1.0.0
  collection: ^1.14.0
  logging: ^0.11.3+1
  test: ^1.3.3
  yaml: ^2.1.13

dependency_overrides:
  built_bloc:
    path: ../built_bloc